import type { Access, CollectionConfig } from 'payload';

import { sanityIdField } from '../fields/sanityId';

/**
 * Responsive sizes generated by sharp at upload time. `fit: 'inside'` keeps the
 * original aspect ratio, and `withoutEnlargement` skips sizes larger than the
 * original. `next/image` picks a size and optimizes the final format on top.
 */
const MEDIA_IMAGE_SIZES = [
  { name: 'thumbnail', width: 400 },
  { name: 'card', width: 800 },
  { name: 'large', width: 1600 },
  { name: 'xl', width: 2400 },
] as const;

/**
 * Files themselves are public: anyone may download one (Blob URLs, or Payload's
 * file route in local-disk mode), and the site reads media through the Local API.
 * Anonymous REST/GraphQL listing is blocked, so photos attached to unpublished
 * drafts cannot be enumerated at /api/media.
 */
export const mediaReadAccess: Access = ({ req, isReadingStaticFile }) =>
  Boolean(req.user) || req.payloadAPI === 'local' || Boolean(isReadingStaticFile);

export const Media: CollectionConfig = {
  slug: 'media',
  admin: {
    useAsTitle: 'alt',
    defaultColumns: ['filename', 'alt', 'updatedAt'],
  },
  access: {
    read: mediaReadAccess,
  },
  fields: [
    sanityIdField,
    {
      name: 'alt',
      type: 'text',
      required: true,
    },
  ],
  upload: {
    mimeTypes: ['image/*'],
    focalPoint: true,
    imageSizes: MEDIA_IMAGE_SIZES.map(({ name, width }) => ({
      name,
      width,
      fit: 'inside',
      withoutEnlargement: true,
    })),
    adminThumbnail: 'thumbnail',
  },
};
