name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NEXT_PUBLIC_SANITY_GRAPHQL_SCHEMA_URL: ${{ secrets.NEXT_PUBLIC_SANITY_GRAPHQL_SCHEMA_URL }}
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
  NEXT_PUBLIC_SANITY_DATASET: 'development'
  NEXT_PUBLIC_SANITY_API_VERSION: '2022-11-28'
  # Test Google Analytics ID
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: 'G-KL7CLHPFFB'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          cache: yarn
          node-version: lts/*
      - run: yarn install --frozen-lockfile
      - run: yarn generate
      - run: yarn run type-check
      - run: yarn run lint -- --max-warnings 0
