name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: '30 6 * * 1'

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: OpenSSF Scorecard Action
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload Scorecard report
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-report
          path: results.sarif
          if-no-files-found: error
